<?php
    include("functions.php");
    session_start();
    $userId=$_SESSION["userId"];
    $userId=$_GET["userId"];
    $actId=$_GET["actId"];
    $content=$_GET["content"];
    include("conn.php");
    $sql="INSERT INTO evaluate (user_id,act_id,content) VALUES (?,?,?);";
    $stmt=mysqli_prepare($conn,$sql);
    mysqli_stmt_bind_param($stmt,"iis",$userId,$actId,$content);
    mysqli_stmt_execute($stmt);
    if(mysqli_affected_rows($conn)>0){
        page_redirect(1,"","评论成功");
    }
    else{
        page_redirect(1,"","评论失败！！！");
    }
    mysqli_stmt_close($stmt);
    mysqli_close($conn);
?>
