<?php
    include("conn.php");
    include("functions.php");
    $actId=$_POST["actId"];
    $actName=$_POST["actName"];
    $content=$_POST["content"];
    $startTime=$_POST["startTime"];
    $endTime=$_POST["endTime"];
    $status=$_POST["status"];
    $signUp=$_POST["signUp"];
    $image=$_POST["image"];
    $sql="update activity set act_name=?,content=?,start_time='$startTime',end_time='$endTime',status=?,sign_up=?,image=? where act_id=?";
    $stmt=mysqli_prepare($conn,$sql);
    mysqli_stmt_bind_param($stmt,"ssiisi",$actName,$content,$status,$signUp,$image,$actId);
    mysqli_stmt_execute($stmt);
    if(mysqli_affected_rows($conn)>0){
        page_redirect(1,"","活动信息修改成功!");
    }
    else{
        page_redirect(1,"","活动信息修改失败!");   
    }
    mysqli_stmt_close($stmt);
    mysqli_close($conn);
?>